vim.opt.backup = false -- don't make backups
vim.opt.backupcopy = 'no'
vim.opt.tabstop = 2 -- number of spaces for tabs
vim.opt.shiftwidth = 2 -- number of spaces for indentation
vim.opt.cursorline = true
vim.opt.expandtab = true -- convert tabs to spaces
vim.wo.number = true -- set numbers
vim.wo.relativenumber = true -- set relative numbers
vim.opt.ignorecase = true -- searching is not case sensitive
vim.opt.smartcase = true -- if pattern contains uppercase then is case sensitive
vim.wo.wrap = false -- no word wrapping
vim.opt.hidden = true
vim.opt.tabstop = 2
vim.opt.foldmethod = 'indent'
vim.opt.foldlevel = 99 -- start unfolded
vim.o.clipboard = "unnamedplus" -- yanking works with system clipboard
vim.opt.termguicolors = true
vim.opt.signcolumn = 'yes' -- signcolumn for marking warnings from lsp, without this one lsp error marker will move the number column on the left
